/*
* ============================================================================
*  Name     : CLemonPlayerDocument from LemonPlayerDocument.h
*  Part of  : LemonPlayer
*  Created  : 17.09.2008 by zengcity
*  Implementation notes:
*     Initial content was generated by Series 60 Application Wizard.
*  Version  :
*  Copyright: 
* ============================================================================
*/

// INCLUDE FILES
#include "LemonPlayerDocument.h"
#include "LemonPlayerAppui.h"

// ================= MEMBER FUNCTIONS =======================

// constructor
CLemonPlayerDocument::CLemonPlayerDocument(CEikApplication& aApp)
: CAknDocument(aApp)    
    {
    }

// destructor
CLemonPlayerDocument::~CLemonPlayerDocument()
    {
    }

// EPOC default constructor can leave.
void CLemonPlayerDocument::ConstructL()
    {
    }

// Two-phased constructor.
CLemonPlayerDocument* CLemonPlayerDocument::NewL(
        CEikApplication& aApp)     // CLemonPlayerApp reference
    {
    CLemonPlayerDocument* self = new (ELeave) CLemonPlayerDocument( aApp );
    CleanupStack::PushL( self );
    self->ConstructL();
    CleanupStack::Pop();

    return self;
    }
    
// ----------------------------------------------------
// CLemonPlayerDocument::CreateAppUiL()
// constructs CLemonPlayerAppUi
// ----------------------------------------------------
//
CEikAppUi* CLemonPlayerDocument::CreateAppUiL()
    {
    return new (ELeave) CLemonPlayerAppUi;
    }

// End of File  
